title: "Microsoft Paginated Reports"
description: "Some things you might not know about Paginated Reports in SSRS, PBIRS, and PowerBI.com"

repository: jt000/PaginatedReportingBlog

url: "https://jt000.github.io"
baseurl: "/PaginatedReportingBlog"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

defaults:
  # _docs
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: single
      comments: true
      related: true
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      related: true
      sidebar:
        nav: "docs"
